# Generated by Django 6.0.4 on 2026-04-23 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("measurement", "0002_sensor_created_at_sensor_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="measurement",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="measurements/"),
        ),
    ]
